apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kulc292rw-nodejs
  janus-idp.io/tekton: kulc292rw-nodejs
  backstage.io/kubernetes-id: kulc292rw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kulc292rw-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
